const ERROR_CODES = Object.freeze({
  ORDER_NOT_ACCEPTABLE: "ORDER_NOT_ACCEPTABLE",
  ORDER_VERSION_CONFLICT: "ORDER_VERSION_CONFLICT",
  FALLBACK_LOCKED: "FALLBACK_LOCKED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION: "VALIDATION",
  UNAUTHORIZED: "UNAUTHORIZED",
});

module.exports = { ERROR_CODES };
